SELECT
  data.TemplateVersion,
  data.Header.AssetClass,
  data.Header.InstrumentType,
  data.Header.UseCase,
  data.Header.Level,
  data.Identifier.UPI,
  data.Identifier.Status,
  data.Identifier.StatusReason,
  data.Identifier.LastUpdateDateTime,
  data.Derived.ClassificationType,
  data.Derived.UnderlyingAssetType,
  data.Derived.SingleorMultiCurrency,
  data.Derived.CFIDeliveryType,
  data.Derived.ShortName,
  data.Derived.UnderlierName,
  cfi.Version AS CFI_Version,
  cfi.VersionStatus AS CFI_VersionStatus,
  cfi.Value AS CFI_Value,
  cfi.Category.Code AS CFI_Category_Code,
  cfi.Category.Value AS CFI_Category_Value,
  cfi.Group.Code AS CFI_Group_Code,
  cfi.Group.Value AS CFI_Group_Value,
  attr.Name AS CFI_Attribute_Name,
  attr.Code AS CFI_Attribute_Code,
  attr.Value AS CFI_Attribute_Value,
  data.Attributes.NotionalCurrency,
  data.Attributes.ReferenceRate,
  data.Attributes.ReferenceRateTermValue,
  data.Attributes.ReferenceRateTermUnit,
  data.Attributes.OtherLegReferenceRate,
  data.Attributes.OtherLegReferenceRateTermValue,
  data.Attributes.OtherLegReferenceRateTermUnit,
  data.Attributes.NotionalSchedule,
  data.Attributes.DeliveryType
FROM
  your_json_table data
LATERAL VIEW explode(data.Derived.CFI) cfiTable AS cfi
LATERAL VIEW explode(cfi.Attributes) attrTable AS attr
